name: CI

on:
  pull_request:

env:
  GSAP_AUTH_TOKEN: ${{ secrets.GSAP_AUTH_TOKEN }}

jobs:
  Lint:
    uses: finsweet/workflow-ci-lint/.github/workflows/lint.yml@main

  # Comment this job out if your project doesn't have any tests
  Tests:
    uses: finsweet/workflow-ci-test/.github/workflows/test.yml@main
