name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GSAP_AUTH_TOKEN: ${{ secrets.GSAP_AUTH_TOKEN }}
