name: Release

on:
  push:
    branches:
      - master
      - main

env:
  GSAP_AUTH_TOKEN: ${{ secrets.GSAP_AUTH_TOKEN }}

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets: inherit
